import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'vi' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  vi: {
    app_title: "CPGVN",
    landing_explore: "Khám Phá Ngay",
    landing_render: "Render Ngoại Thất",
    landing_edit: "Chỉnh Sửa Ảnh",
    landing_utils: "Tiện Ích",
    landing_tour: "Virtual Tour",
    tab_exterior: "Ngoại Thất",
    tab_interior: "Nội Thất",
    tab_masterplan: "Masterplan 3D",
    tab_floorplan: "Layout 2D->3D",
    tab_tour: "Virtual Tour",
    tab_edit: "Chỉnh Sửa",
    tab_utils: "Tiện Ích",
    step_1: "1. Tải Lên",
    step_2: "2. Cấu Hình",
    step_3: "3. Góc Nhìn",
    res_title: "Kết Quả",
    res_empty: "Chưa có ảnh nào được tạo.",
    res_zoom: "Phóng To",
    res_edit: "Sửa",
    res_video: "Video",
    res_angle: "Tạo Góc Khác",
    res_upscale_2k: "Upscale 2K",
    res_upscale_4k: "Upscale 4K",
    btn_download: "Tải Xuống",
    btn_generate: "Tạo Hình Ảnh",
    btn_upload: "Tải Ảnh Lên",
    btn_change_image: "Đổi Ảnh",
    btn_converting: "Đang Chuyển Đổi...",
    btn_convert_sketch: "Chuyển Sang Nét Vẽ",
    btn_remove: "Xóa",
    ext_custom_prompt: "Mô tả ý tưởng của bạn...",
    ext_context: "Bối cảnh",
    ext_select_context: "-- Chọn bối cảnh --",
    ext_lighting: "Ánh sáng",
    ext_select_light: "-- Chọn ánh sáng --",
    ext_weather: "Thời tiết",
    ext_select_weather: "-- Chọn thời tiết --",
    ext_tone: "Tông màu",
    ext_select_tone: "-- Chọn tông màu --",
    int_function: "Chức năng phòng",
    int_style: "Phong cách",
    int_light: "Ánh sáng",
    int_custom_ph: "Nhập tùy chọn khác...",
    fp_room_type: "Loại phòng",
    fp_style: "Phong cách",
    fp_generate: "Render Layout 2D->3D",
    fp_create_angle: "Tạo Góc Nhìn",
    opt_num_images: "Số lượng ảnh",
    opt_aspect_ratio: "Tỷ lệ khung hình",
    opt_auto: "Tự động",
    hist_exterior: "Lịch Sử Ngoại Thất",
    hist_interior: "Lịch Sử Nội Thất",
    hist_floorplan: "Lịch Sử Layout 2D->3D",
    hist_edit: "Lịch Sử Chỉnh Sửa",
    hist_diagram: "Lịch Sử Diagram",
    hist_empty: "Chưa có lịch sử.",
    hist_clear: "Xóa toàn bộ lịch sử",
    guide_title: "Hướng Dẫn Sử Dụng",
    guide_tab_general: "Chung",
    guide_tab_exterior: "Ngoại Thất",
    guide_tab_interior: "Nội Thất",
    guide_tab_floorplan: "Layout 2D->3D",
    guide_tab_tour: "Virtual Tour",
    guide_tab_edit: "Chỉnh Sửa",
    guide_tab_utils: "Tiện Ích",
    guide_gen_title: "Giới Thiệu Chung",
    guide_gen_desc: "Chào mừng bạn đến với CPG AI Architect - công cụ hỗ trợ thiết kế kiến trúc bằng AI.",
    guide_gen_step1: "Chọn tab chức năng phù hợp (Ngoại thất, Nội thất, v.v.).",
    guide_gen_step2: "Tải lên ảnh hiện trạng hoặc bản vẽ phác thảo.",
    guide_gen_step3: "Nhập mô tả hoặc chọn các thiết lập có sẵn.",
    guide_gen_step4: "Nhấn nút 'Tạo' và chờ kết quả.",
    guide_ext_title: "Render Ngoại Thất",
    guide_ext_desc: "Biến ảnh hiện trạng hoặc ảnh phác thảo thành phối cảnh ngoại thất hoàn chỉnh.",
    guide_ext_step1: "Tải ảnh công trình.",
    guide_ext_step2: "Thêm ảnh tham khảo (nếu có) để định hướng phong cách.",
    guide_ext_step3: "Chọn bối cảnh, ánh sáng, thời tiết.",
    guide_ext_step4: "Sử dụng tính năng 'Tạo Góc Khác' để render góc nhìn mới.",
    guide_int_title: "Render Nội Thất",
    guide_int_desc: "Thiết kế nội thất từ ảnh phòng thô hoặc phác thảo.",
    guide_int_step1: "Tải ảnh phòng. Dùng 'Chuyển Sang Nét Vẽ' nếu cần concept.",
    guide_int_step2: "Chọn chức năng phòng và phong cách.",
    guide_int_step3: "Tạo phương án.",
    guide_fp_title: "Render Layout 2D->3D",
    guide_fp_desc: "Dựng phối cảnh 3D từ bản vẽ layout 2D.",
    guide_fp_step1: "Tải ảnh layout 2D.",
    guide_fp_step2: "Chọn loại phòng và phong cách.",
    guide_fp_step3: "Tạo hình ảnh 3D.",
    guide_tour_title: "Virtual Tour",
    guide_tour_desc: "Tạo trải nghiệm tham quan ảo từ một hình ảnh tĩnh.",
    guide_tour_step1: "Tải ảnh phối cảnh.",
    guide_tour_step2: "Sử dụng các nút điều hướng để di chuyển camera.",
    guide_tour_step3: "Áp dụng hiệu ứng môi trường (Ngày, Đêm, Tuyết...).",
    guide_edit_title: "Chỉnh Sửa Ảnh (Inpainting)",
    guide_edit_desc: "Thêm, xóa hoặc thay đổi chi tiết trong ảnh.",
    guide_edit_step1: "Tải ảnh hoặc chọn từ kết quả render.",
    guide_edit_step2: "Tô lên vùng cần chỉnh sửa (Mask).",
    guide_edit_step3: "Nhập mô tả thay đổi mong muốn.",
    guide_utils_title: "Tiện Ích Mở Rộng",
    guide_utils_desc: "Các công cụ hỗ trợ chuyên sâu khác.",
    guide_utils_mood: "Tạo bảng mood board từ ý tưởng.",
    guide_utils_finish: "Hoàn thiện các chi tiết xây dựng.",
    footer_quick_links: "Liên Kết Nhanh",
    footer_hcm: "Văn Phòng TP.HCM",
    footer_hn: "Văn Phòng Hà Nội",
    footer_rights: "© 2024 CPG Vietnam. All rights reserved.",
    drag_drop: "Nhấp hoặc kéo thả ảnh vào đây",
    drag_drop_sub: "Hỗ trợ PNG, JPG, WEBP",
    angle_top_down: "Trên Cao Nhìn Xuống",
    angle_low: "Góc Thấp (Worm's Eye)",
    angle_34_left: "Góc 3/4 Trái",
    angle_wide: "Góc Rộng Toàn Cảnh",
    angle_close: "Cận Cảnh Chi Tiết",
    angle_34_right: "Góc 3/4 Phải",
    angle_front: "Trực Diện",
    angle_placeholder: "-- Chọn gợi ý góc nhìn --",
    angle_selected: "Góc Đã Chọn",
    angle_select: "Chọn Góc Trên Visual",
    angle_selected_count: "Đã chọn",
    angle_desc_ph: "Mô tả chi tiết góc nhìn mong muốn...",
    generated_count: "Đã tạo:",
    util_diagram_title: "Tạo Diagram",
    util_diagram_desc: "Tạo các sơ đồ phân tích, axonometric, hoặc exploded view từ ảnh công trình.",
    util_diagram_step1: "1. Tải Lên Ảnh Công Trình",
    util_diagram_step2: "2. Chọn Loại Diagram",
    util_diagram_select_ph: "-- Chọn loại sơ đồ --",
    util_diagram_type_exploded: "Phối Cảnh Phân Tầng (Exploded Axonometric)",
    util_diagram_type_analysis: "Sơ Đồ Phân Tích (Analysis Diagram)",
    // FIX: Removed duplicate 'util_diagram_type_axo' property
    util_diagram_type_axo: "Phối Cảnh Axonometric (3D Massing)",
    util_diagram_notes_ph: "Ghi chú thêm (Ví dụ: Nhấn mạnh lối vào, màu đỏ...)",
    util_diagram_btn: "Tạo Diagram",
    util_diagram_generating: "Đang Tạo Sơ Đồ...",
    util_expand_title: "Mở Rộng Khung Hình",
    util_expand_desc: "Mở rộng không gian ảnh sang các tỷ lệ khác (16:9, 9:16...).",
    util_expand_step1: "1. Tải Ảnh Gốc",
    util_expand_step2: "2. Chọn Tỷ Lệ & Mô Tả",
    util_expand_ratio: "Tỷ lệ đích",
    util_expand_prompt_ph: "Mô tả phần mở rộng (VD: bầu trời xanh, sân vườn rộng...)",
    util_expand_btn: "Mở Rộng Ảnh",
    util_expand_generating: "Đang mở rộng...",
    util_presentation_title: "Dàn Trang (Presentation)",
    util_presentation_desc: "Tạo bảng trình bày concept kiến trúc tự động.",
    api_key_title: "Gemini API Key",
    api_key_placeholder: "Dán API Key của bạn vào đây (AI Studio)...",
    api_key_desc: "Bạn cần cung cấp Gemini API Key để sử dụng tính năng AI. Hướng dẫn: 1. Truy cập aistudio.google.com 2. Chọn 'Create API key' 3. Dán mã vào đây. Khóa được lưu cục bộ trên trình duyệt của bạn.",
    api_key_save: "Lưu Cấu Hình",
    api_key_success: "Đã cập nhật API Key thành công!",
    api_key_missing: "Vui lòng nhập API Key để bắt đầu.",
  },
  en: {
    app_title: "CPGVN",
    landing_explore: "Explore Now",
    landing_render: "Exterior Render",
    landing_edit: "Edit Image",
    landing_utils: "Utilities",
    landing_tour: "Virtual Tour",
    tab_exterior: "Exterior",
    tab_interior: "Interior",
    tab_masterplan: "Masterplan 3D",
    tab_floorplan: "Layout 2D->3D",
    tab_tour: "Virtual Tour",
    tab_edit: "Edit",
    tab_utils: "Utilities",
    step_1: "1. Upload",
    step_2: "2. Configure",
    step_3: "3. View Angle",
    res_title: "Result",
    res_empty: "No images generated yet.",
    res_zoom: "Zoom",
    res_edit: "Edit",
    res_video: "Video",
    res_angle: "New Angle",
    res_upscale_2k: "Upscale 2K",
    res_upscale_4k: "Upscale 4K",
    btn_download: "Download",
    btn_generate: "Generate",
    btn_upload: "Upload Image",
    btn_change_image: "Change Image",
    btn_converting: "Converting...",
    btn_convert_sketch: "Convert to Sketch",
    btn_remove: "Remove",
    ext_custom_prompt: "Describe your idea...",
    ext_context: "Context",
    ext_select_context: "-- Select Context --",
    ext_lighting: "Lighting",
    ext_select_light: "-- Select Lighting --",
    ext_weather: "Weather",
    ext_select_weather: "-- Select Weather --",
    ext_tone: "Tone",
    ext_select_tone: "-- Select Tone --",
    int_function: "Room Function",
    int_style: "Style",
    int_light: "Lighting",
    int_custom_ph: "Enter custom...",
    fp_room_type: "Room Type",
    fp_style: "Style",
    fp_generate: "Render Layout 2D->3D",
    fp_create_angle: "Create View",
    opt_num_images: "Number of Images",
    opt_aspect_ratio: "Aspect Ratio",
    opt_auto: "Auto",
    hist_exterior: "Exterior History",
    hist_interior: "Interior History",
    hist_floorplan: "Layout 2D->3D History",
    hist_edit: "Edit History",
    hist_diagram: "Diagram History",
    hist_empty: "No history yet.",
    hist_clear: "Clear All History",
    guide_title: "User Guide",
    guide_tab_general: "General",
    guide_tab_exterior: "Exterior",
    guide_tab_interior: "Interior",
    guide_tab_floorplan: "Layout 2D->3D",
    guide_tab_tour: "Virtual Tour",
    guide_tab_edit: "Edit",
    guide_tab_utils: "Utilities",
    guide_gen_title: "General Introduction",
    guide_gen_desc: "Welcome to CPG AI Architect - AI-powered architectural design support tool.",
    guide_gen_step1: "Select function tab (Exterior, Interior, etc.).",
    guide_gen_step2: "Upload existing photo or sketch.",
    guide_gen_step3: "Enter description or select presets.",
    guide_gen_step4: "Click 'Generate' and wait for results.",
    guide_ext_title: "Exterior Render",
    guide_ext_desc: "Transform existing photos or sketches into complete exterior perspectives.",
    guide_ext_step1: "Upload building photo.",
    guide_ext_step2: "Add reference image (optional) for style direction.",
    guide_ext_step3: "Select context, lighting, weather.",
    guide_ext_step4: "Use 'New Angle' to render new perspectives.",
    guide_int_title: "Interior Render",
    guide_int_desc: "Design interior from raw room photo or sketch.",
    guide_int_step1: "Upload room photo. Use 'Convert to Sketch' if concept needed.",
    guide_int_step2: "Select room function and style.",
    guide_int_step3: "Generate options.",
    guide_fp_title: "Layout 2D->3D Render",
    guide_fp_desc: "Build 3D perspective from 2D layout drawing.",
    guide_fp_step1: "Upload 2D layout image.",
    guide_fp_step2: "Select room type and style.",
    guide_fp_step3: "Generate 3D image.",
    guide_tour_title: "Virtual Tour",
    guide_tour_desc: "Create virtual tour experience from a static image.",
    guide_tour_step1: "Upload perspective image.",
    guide_tour_step2: "Use navigation buttons to move camera.",
    guide_tour_step3: "Apply environment effects (Day, Night, Snow...).",
    guide_edit_title: "Image Editing (Inpainting)",
    guide_edit_desc: "Add, remove or change details in image.",
    guide_edit_step1: "Upload image or select from render result.",
    guide_edit_step2: "Paint over area to edit (Mask).",
    guide_edit_step3: "Enter description of desired change.",
    guide_utils_title: "Extended Utilities",
    guide_utils_desc: "Other specialized support tools.",
    guide_utils_mood: "Create mood board from ideas.",
    guide_utils_finish: "Complete construction details.",
    footer_quick_links: "Quick Links",
    footer_hcm: "HCMC Office",
    footer_hn: "Hanoi Office",
    footer_rights: "© 2024 CPG Vietnam. All rights reserved.",
    drag_drop: "Click or drag & drop image here",
    drag_drop_sub: "Supports PNG, JPG, WEBP",
    angle_top_down: "Top-Down View",
    angle_low: "Low Angle (Worm's Eye)",
    angle_34_left: "3/4 Left View",
    angle_wide: "Wide Angle",
    angle_close: "Close-up Detail",
    angle_34_right: "3/4 Right View",
    angle_front: "Front View",
    angle_placeholder: "-- Select Angle Suggestion --",
    angle_selected: "Selected Angle",
    angle_select: "Select Angle on Visual",
    angle_desc_ph: "Describe desired view angle details...",
    generated_count: "Generated:",
    util_diagram_title: "Create Diagram",
    util_diagram_desc: "Create analysis diagrams, axonometric, or exploded views from building photos.",
    util_diagram_step1: "1. Upload Building Image",
    util_diagram_step2: "2. Select Diagram Type",
    util_diagram_select_ph: "-- Select diagram type --",
    util_diagram_type_exploded: "Exploded Axonometric",
    util_diagram_type_analysis: "Analysis Diagram",
    util_diagram_type_axo: "Axonometric (3D Massing)",
    util_diagram_notes_ph: "Extra notes (e.g. highlight entrance, red color...)",
    util_diagram_btn: "Create Diagram",
    util_diagram_generating: "Generating Diagram...",
    util_expand_title: "Expand Image",
    util_expand_desc: "Expand image canvas to other aspect ratios (16:9, 9:16...).",
    util_expand_step1: "1. Upload Original Image",
    util_expand_step2: "2. Select Ratio & Prompt",
    util_expand_ratio: "Target Ratio",
    util_expand_prompt_ph: "Describe expansion (e.g. blue sky, wide garden...)",
    util_expand_btn: "Expand Image",
    util_expand_generating: "Expanding...",
    util_presentation_title: "Presentation Board",
    util_presentation_desc: "Auto-generate architectural concept boards.",
    api_key_title: "Gemini API Key",
    api_key_placeholder: "Paste your API Key here...",
    api_key_desc: "You need a Gemini API Key to use AI features. Steps: 1. Visit aistudio.google.com 2. Click 'Create API key' 3. Paste the key here. It is stored locally in your browser.",
    api_key_save: "Save Key",
    api_key_success: "API Key updated successfully!",
    api_key_missing: "Please enter an API Key to proceed.",
  },
  zh: {
    app_title: "CPGVN",
    landing_explore: "立即探索",
    landing_render: "外观渲染",
    landing_edit: "图像编辑",
    landing_utils: "实用工具",
    landing_tour: "虚拟漫游",
    tab_exterior: "外观",
    tab_interior: "室内",
    tab_masterplan: "总体规划 3D",
    tab_floorplan: "Layout 2D->3D",
    tab_tour: "虚拟漫游",
    tab_edit: "编辑",
    tab_utils: "工具",
    step_1: "1. 上传",
    step_2: "2. 配置",
    step_3: "3. 视角",
    res_title: "结果",
    res_empty: "尚未生成图像。",
    res_zoom: "放大",
    res_edit: "编辑",
    res_video: "视频",
    res_angle: "新角度",
    res_upscale_2k: "放大 2K",
    res_upscale_4k: "放大 4K",
    btn_download: "下载",
    btn_generate: "生成",
    btn_upload: "上传图像",
    btn_change_image: "更改图像",
    btn_converting: "转换中...",
    btn_convert_sketch: "转换为草图",
    btn_remove: "移除",
    ext_custom_prompt: "描述您的想法...",
    ext_context: "环境",
    ext_select_context: "-- 选择环境 --",
    ext_lighting: "光照",
    ext_select_light: "-- 选择光照 --",
    ext_weather: "天气",
    ext_select_weather: "-- 选择天气 --",
    ext_tone: "色调",
    ext_select_tone: "-- 选择色调 --",
    int_function: "房间功能",
    int_style: "风格",
    int_light: "光照",
    int_custom_ph: "输入自定义...",
    fp_room_type: "房间类型",
    fp_style: "风格",
    fp_generate: "渲染 Layout 2D->3D",
    fp_create_angle: "创建视图",
    opt_num_images: "图像数量",
    opt_aspect_ratio: "纵横比",
    opt_auto: "自动",
    hist_exterior: "外观历史",
    hist_interior: "室内历史",
    hist_floorplan: "Layout 2D->3D 历史",
    hist_edit: "编辑历史",
    hist_diagram: "图表历史",
    hist_empty: "暂无历史记录。",
    hist_clear: "清除所有历史",
    guide_title: "用户指南",
    guide_tab_general: "常规",
    guide_tab_exterior: "外观",
    guide_tab_interior: "室内",
    guide_tab_floorplan: "Layout 2D->3D",
    guide_tab_tour: "虚拟漫游",
    guide_tab_edit: "编辑",
    guide_tab_utils: "工具",
    guide_gen_title: "概览",
    guide_gen_desc: "欢迎使用 CPG AI Architect - AI 驱动的建筑设计辅助工具。",
    guide_gen_step1: "选择功能选项卡（外观、室内等）。",
    guide_gen_step2: "上传现有照片或草图。",
    guide_gen_step3: "输入描述或选择预设。",
    guide_gen_step4: "点击“生成”并等待结果。",
    guide_ext_title: "外观渲染",
    guide_ext_desc: "将现有照片或草图转换为完整的外观透视图。",
    guide_ext_step1: "上传建筑照片。",
    guide_ext_step2: "添加参考图像（可选）以指导风格。",
    guide_ext_step3: "选择环境、光照、天气。",
    guide_ext_step4: "使用“新角度”渲染新视角。",
    guide_int_title: "室内渲染",
    guide_int_desc: "从原始房间照片或草图设计室内。",
    guide_int_step1: "上传房间照片。如果需要概念，请使用“转换为草图”。",
    guide_int_step2: "选择房间功能和风格。",
    guide_int_step3: "生成方案。",
    guide_fp_title: "Layout 2D->3D 渲染",
    guide_fp_desc: "从 2D layout 构建 3D 透视图。",
    guide_fp_step1: "上传 2D layout 图像。",
    guide_fp_step2: "选择房间类型和风格。",
    guide_fp_step3: "生成 3D 图像。",
    guide_tour_title: "虚拟漫游",
    guide_tour_desc: "从静态图像创建虚拟漫游体验。",
    guide_tour_step1: "上传透视图图像。",
    guide_tour_step2: "使用导航按钮移动相机。",
    guide_tour_step3: "应用环境效果（白天、夜晚、雪...）。",
    guide_edit_title: "图像编辑 (Inpainting)",
    guide_edit_desc: "在图像中添加、删除或更改细节。",
    guide_edit_step1: "上传图像或从渲染结果中选择。",
    guide_edit_step2: "涂抹需要编辑的区域（蒙版）。",
    guide_edit_step3: "输入所需更改的描述。",
    guide_utils_title: "扩展工具",
    guide_utils_desc: "其他专业支持工具。",
    guide_utils_mood: "从创意创建情绪板。",
    guide_utils_finish: "完成施工细节。",
    footer_quick_links: "快速链接",
    footer_hcm: "胡志明市办事处",
    footer_hn: "河内办事处",
    footer_rights: "© 2024 CPG Vietnam. All rights reserved.",
    drag_drop: "点击或拖放图像到此处",
    drag_drop_sub: "支持 PNG, JPG, WEBP",
    angle_top_down: "俯视图",
    angle_low: "低角度 (仰视)",
    angle_34_left: "左侧 3/4 视图",
    angle_wide: "广角",
    angle_close: "特写细节",
    angle_34_right: "右侧 3/4 视图",
    angle_front: "正视图",
    angle_placeholder: "-- 选择建议角度 --",
    angle_selected: "已选角度",
    angle_select: "在视图上选择角度",
    angle_desc_ph: "描述所需的视角细节...",
    generated_count: "已生成：",
    util_diagram_title: "创建图表",
    util_diagram_desc: "从建筑照片创建分析图、轴测图或爆炸图。",
    util_diagram_step1: "1. 上传建筑图像",
    util_diagram_step2: "2. 选择图表类型",
    util_diagram_select_ph: "-- 选择图表类型 --",
    util_diagram_type_exploded: "爆炸轴测图",
    util_diagram_type_analysis: "分析图",
    util_diagram_type_axo: "轴测图 (3D 体块)",
    util_diagram_notes_ph: "额外说明（例如：突出入口，红色...）",
    util_diagram_btn: "创建图表",
    util_diagram_generating: "正在生成图表...",
    util_expand_title: "扩展图像",
    util_expand_desc: "将图像画布扩展到其他比例（16:9, 9:16...）。",
    util_expand_step1: "1. 上传原始图像",
    util_expand_step2: "2. 选择比例和提示",
    util_expand_ratio: "目标比例",
    util_expand_prompt_ph: "描述扩展部分（例如：蓝天，宽阔的花园...）",
    util_expand_btn: "扩展图像",
    util_expand_generating: "正在扩展...",
    util_presentation_title: "演示板",
    util_presentation_desc: "自动生成建筑概念板。",
    api_key_title: "Gemini API Key",
    api_key_placeholder: "在此处粘贴您的 API 密钥...",
    api_key_desc: "您需要提供个人 Gemini API 密钥才能使用此应用程序。密钥安全地存储在浏览器的本地存储中。",
    api_key_save: "保存密钥",
    api_key_success: "API 密钥更新成功！",
    api_key_missing: "请输入 API 密钥以继续。",
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('vi');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
